# Site settings
title: Armen Vartan
email: vartan.armen@gmail.com
description: Amateur Learner
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: armenvartan1
github_username:  armenvartan

# Build settings
markdown: kramdown
